name: auto_mappr_annotation
description: Mapping between different objects with ease
version: 1.0.0
repository: https://github.com/netglade/auto_mappr
issue_tracker: https://github.com/netglade/auto_mappr/issues

environment:
  sdk: ">=2.18.7 <3.0.0"

dev_dependencies:
  dart_code_metrics: ^5.7.0
  netglade_analysis: 1.1.2
  test: ^1.16.0
