include: package:netglade_analysis/lints.yaml

analyzer:
  exclude: 
    - test/fixture/fixtures/**
  plugins:
    - dart_code_metrics
  
dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  rules:
    - format-comment: false
    - avoid-non-null-assertion: false
    - avoid-top-level-members-in-tests: false
