include: package:netglade_analysis/lints_package.yaml

analyzer:
  exclude: 
    - test/fixture/fixtures/**
  plugins:
    - dart_code_metrics
  
linter:
  rules:
    - public_member_api_docs: false

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  rules:
    - missing-test-assertion: false  
    - format-comment: false
    - avoid-non-null-assertion: false
    - avoid-top-level-members-in-tests: false
