builders:
  auto_mapper:
    import: "package:auto_mapper/builder.dart"
    builder_factories: ["automapperBuilder"]
    build_extensions: { ".dart": ["mapper.g.dart"] }
    auto_apply: dependents
    build_to: source

  #  applies_builders: ["source_gen|combining_builder"]
   # required_inputs: [".g.dart"]
