name: auto_mapper
description: Mapping between different objects with ease
version: 0.1.0
repository: https://github.com/netglade/auto_mapper
issue_tracker: https://github.com/netglade/auto_mapper/issues

environment:
  sdk: ">=2.18.7 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  dart_code_metrics: ^5.5.1
  netglade_analysis: 1.1.2
  test: ^1.16.0
