name: auto_mapper_example
description: Example project for AutoMapper
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.7 <3.0.0"

dependencies:
  auto_mapper_annotation: ^0.1.0
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  auto_mapper: ^0.0.1
  build_runner: ^2.0.0
