name: my_project

packages:
  - packages/**
  - example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  gen:
    run: melos exec -- dart run build_runner watch --delete-conflicting-outputs
    packageFilters:
      scope: '*example*'
  gen:test:
    run: melos exec -- dart run build_runner watch --delete-conflicting-outputs
    packageFilters:
      dirExists:
        - test
