name: auto_mappr_workspace

packages:
  - packages/**
  - packages/**/example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  # ANALYZING

  lint:all:
    run: melos run lint:dart && melos run lint:dcm
    description: Run all static analysis checks.

  lint:dart:
    run: melos exec -c 10 -- dart analyze --fatal-infos
    description: Run `flutter analyze` for all packages.

  lint:dcm:
    run: melos exec -c 10 -- dart analyze --fatal-infos
    description: Run `flutter analyze` for all packages.

  # GENERATION

  gen:build-all:
    run: melos run gen:example:build && melos run gen:test:build
    description: Run `flutter analyze` for all packages.

  gen:example:
    run: melos exec -- dart run build_runner watch --delete-conflicting-outputs
    packageFilters:
      scope: '*example*'

  gen:example:build:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      scope: '*example*'

  gen:test:
    run: melos exec -- dart run build_runner watch --delete-conflicting-outputs
    packageFilters:
      dirExists:
        - test

  gen:test:build:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dirExists:
        - test

  # TESTING

  test:
    run: melos exec -- dart test
    packageFilters:
      dirExists: test
    description: Run all Dart tests in this project.
