name: auto_mappr_example
description: Example project
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.7 <3.0.0"

dependencies:
  auto_mappr_annotation:
    path: ../../auto_mappr_annotation
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0

dev_dependencies:
  auto_mappr:
    path: ../
  build_runner: ^2.0.0
  freezed: ^2.3.2
  lints: ^2.0.0
  netglade_analysis: 1.2.0
  test: ^1.16.0
