include: package:netglade_analysis/lints.yaml

analyzer:
  exclude:
    - test/integration/error_fixture/**

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  pubspec-rules:
    prefer-publish-to-none: false
  rules:
    avoid-unnecessary-call: false # the Expression API uses a lot of `.call` which is clearer
    avoid-top-level-members-in-tests:
      exclude:
        - test/integration/fixture/**
    avoid-non-null-assertion: false # TODO
    avoid-nullable-interpolation: false # TODO
