include: package:netglade_analysis/lints.yaml

analyzer:
  exclude:
    - test/integration/error_fixture/**

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  pubspec-rules:
    prefer-publish-to-none: false
  rules:
    # TODO: has to be fixed in this package
    avoid-non-null-assertion: false
    avoid-top-level-members-in-tests:
      exclude:
        - test/integration/fixture/**
    # TODO: new analysis will have new DCM config
    avoid-long-parameter-list: false
