name: auto_mappr
description: Mapping between different objects with ease
version: 0.1.0
repository: https://github.com/netglade/auto_mappr
issue_tracker: https://github.com/netglade/auto_mappr/issues

environment:
  sdk: ">=2.18.7 <3.0.0"

dependencies:
  analyzer: ^5.4.0
  auto_mappr_annotation: ^0.1.0
  build: ^2.3.1
  code_builder: ^4.4.0
  collection: ^1.17.0
  equatable: ^2.0.5
  path: ^1.8.2
  source_gen: ^1.2.6

dev_dependencies:
  build_runner: ^2.0.0
  dart_code_metrics: ^5.7.0
  generator_test: ^0.2.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  netglade_analysis: 1.1.2
  source_gen_test: ^1.0.4
  test: ^1.16.0
