name: auto_mapper_generator
description: Mapping between different objects with ease
version: 0.1.0
repository: https://github.com/netglade/auto_mapper
issue_tracker: https://github.com/netglade/auto_mapper

# homepage: https://www.example.com

environment:
  sdk: ">=2.18.7 <3.0.0"

dependencies:
  auto_mapper: ^0.1.0
  analyzer: ^5.4.0
  build: ^2.3.1
  code_builder: ^4.4.0
  path: ^1.8.3
  source_gen: ^1.2.6
  collection: ^1.17.0
  equatable: ^2.0.5

dev_dependencies:
  dart_code_metrics: ^5.5.1
  generator_test: ^0.2.0
  netglade_analysis: 1.1.2
  source_gen_test: ^1.0.4
  test: ^1.16.0
