name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  auto_mappr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: bluefireteam/melos-action@v2

      - name: Generate AutoMappr files
        run: melos run gen:build-all

      - name: Analyze
        run: melos run lint:all

      - name: Install DCM
        run: |
          sudo apt-get update
          wget -qO- https://dcm.dev/pgp-key.public | sudo gpg --dearmor -o /usr/share/keyrings/dcm.gpg
          echo 'deb [signed-by=/usr/share/keyrings/dcm.gpg arch=amd64] https://dcm.dev/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
          sudo apt-get update
          sudo apt-get install dcm

      - name: DCM Analyze
        run: dcm analyze --reporter=github --ci-key ${{ secrets.DCM_KEY }} --email ${{ secrets.DCM_EMAIL }} --fatal-style --fatal-performance --fatal-warnings .

      - name: Test
        run: melos run test
