name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  auto_mappr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: bluefireteam/melos-action@v2

      - name: Generate AutoMappr files
        run: melos run gen:build-all

      - name: Analyze
        run: melos run lint:all

      - name: Test
        run: melos run test
